### ISSUE TITLE
certificate self signing issue

### ISSUE THREAD

**Issue by mithunhegde-egov** [nordic-institute/X-Road#1899]
Hi, I am unable to self sign the ca.cert.pem certificate generated. get this error on trying to sign from the form or manually
Error:
Unable to load X509 request
804B4FDE057F0000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1188:
804B4FDE057F0000:error:0688010A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:349:Type=X509_REQ

cert is generated using steos mentioned in docker cs setup steps. please let me know what can be done to resolve this as it is causing issue while importing the signing certificate from the security server.

Regards,
Mithun

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! There's no need to sign the test CA's root certificate ( `ca.cert.pem`). It's enough to add it to the Central Server as described [here](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#1.3-Adding-certification-service).

**Comment by mithunhegde-egov** [comment]
thank you very much for the response. does the same apply for tsa and ocsp certificate also while configuring the central server? (tsa.cert.pem and ocs.cert.pem)

**Comment by petkivim** [comment]
Yes, the same applies to `ocs.cert.pem` and `tsa.cert.pem` too. It's enough to upload them to the Central Server following the [configuration guide](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#1.3-Adding-certification-service).

**Comment by mithunhegde-egov** [comment]
thank you. I have another query. can we have the security server in the same machine in different ports for testing?if yes what address do I enter to register the authentication certificate. trying enter the full address https://<ip>:<security_server_port> getting invalid request for the same

**Comment by mithunhegde-egov** [comment]
thank you. unable to add wsdl copied from the central server management services. throws this error-WSDL download failed
ID: 2dca780e1b8742bd.

**Comment by petkivim** [comment]
Have you checked the `/var/log/xroad/proxy_ui_api.log` log file for more details?

**Comment by mithunhegde-egov** [comment]
yes. issue is with the connection. not able to connect at this address http://3.111.118.35/managementservices.wsdl. wanted to understand if any port needs to be mapped from the container for wsdl

**Comment by petkivim** [comment]
The management Security Server needs to be able to access the Central Server port `80` in order to fetch the WSDL file. Currently, you're using `3.111.118.35` as the Central Server address. Please make sure that the Security Server is able to access the Central Server using the public IP address. More information about the Security Server network configuration is available [here](https://docs.x-road.global/Manuals/ig-ss_x-road_v6_security_server_installation_guide.html#221-network-diagram) and the Central Server network configuration is available [here](https://docs.x-road.global/Manuals/ig-cs_x-road_6_central_server_installation_guide.html#221-network-diagram). The port `80` is missing from the diagram between the management Security Server and the Central Server, but it's required too.

**Comment by mithunhegde-egov** [comment]
sure thank you. In the last step of the configuration I am getting error_code.core.Server.ClientProxy.SslAuthenticationFailed
Security server has no valid authentication certificate when I try to register TEST as a client. can we add a provider and consumer both to the same security server? even the authentication certificates and signing certificates(the one with .der downloaded) does not need any signing? used the csr html form to sign.

**Comment by petkivim** [comment]
The error message means that the Security Server where you try to register the subsystem doesn't have a valid authentication certificate. More information about the cause of the error can be found [here](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/4915550/How+to+Interpret+Security+Server+Proxy+Error+Messages). Please search with `Server.ClientProxy.SslAuthenticationFailed`.

A service provider and service consumer can share the same Security Server. Both auth and sign certificates need to be signed by the test CA. The required steps for generating the CSRs and importing the certificates can be found [here](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#3.4-Creating-the-certificate-requests). Instead, the Test CA documentation is available [here](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md).

**Comment by mithunhegde-egov** [comment]
the authentication cert status is GOOD. I have added signed certs only. the error changed to **400 bad request now-**  when trying to register.cannot find about this error anywhere in the doc. please share any link for reference

2023-12-12T12:20:19.539Z [https-jsse-nio-4000-exec-4] correlation-id:[116fb988fad675a3] INFO  ee.ria.xroad.common.AuditLogger - {"event":"Register client failed","user":"xrd","ipaddress":"106.51.69.20","reason":"Server.ServerProxy.ServiceFailed.HttpError: Server responded with error 400: Bad Request","warning":false,"auth":"Session","url":"/api/v1/clients/EGOV%3AEGOV%3A1234%3ATESTCLIENT/register","data":{"clientIdentifier":{"memberClass":"EGOV","memberCode":"1234","subsystemCode":"TESTCLIENT","fieldsForStringFormat":["EGOV","1234","TESTCLIENT"],"objectType":"SUBSYSTEM","xroadInstance":"EGOV"}}}
2023-12-12T12:20:19.540Z [https-jsse-nio-4000-exec-4] correlation-id:[116fb988fad675a3] ERROR o.n.x.r.e.ApplicationExceptionHandler - exception caught
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.ServiceFailed.HttpError: Server responded with error 400: Bad Request

**Comment by mithunhegde-egov** [comment]
thank you the setup is complete. I have security server docker container port 80 mapped to port 6000 of my host. I am trying to make rest api call from the client service using https://<ip>:6000/<xroad service id> but not able to connect to port 6000 in the server. I see that it is listening but throws connection refused error- 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.egov.enc.Main.main(Main.java:12)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://3.111.118.35:1000/r1/EGOV/EGOV/1234/MDMS/MDMSService/egov-mdms-service/v1/_search": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:746)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:447)
	at org.egov.enc.services.KeyManagementService.getTenantIds(KeyManagementService.java:191)
	at org.egov.enc.services.KeyManagementService.makeComprehensiveListOfTenantIds(KeyManagementService.java:120)
	at org.egov.enc.services.KeyManagementService.generateKeyForNewTenants(KeyManagementService.java:106)
	at org.egov.enc.services.KeyManagementService.init(KeyManagementService.java:67)
	at org.egov.enc.services.KeyManagementService.run(KeyManagementService.java:208)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	... 5 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	
can you please share something for reference or what I am doing wrong here.

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! Since you have mapped the container port `80` to port `6000`, you should use `http` and not `https`. Instead, if you want to use `https`, you should map the container port `443` to port `6000`. In that case, you should change the client subsystem connection type from `HTTPS` to `HTTP NOAUTH`. More information about the client subsystem connection type is available [here](https://docs.x-road.global/Manuals/ug-ss_x-road_6_security_server_user_guide.html#91-communication-with-service-consumer-information-systems).

**Comment by mithunhegde-egov** [comment]
I did those changes. I am unable to curl also to the port mapped with the 80 port in the security server. central server I am able to ping with the port mapped with docker container's port 80.

**Comment by petkivim** [comment]
What's the error message when you try to submit a request to the Security Server port `80` that's mapped to the container port `443`?

**Comment by mithunhegde-egov** [comment]
I have changed to using http and using port 80 of the container only still. I am getting this connection refused error
in(Main.java:12)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://<ip_add>:<port_id>/r1/EGOV/EGOV/1234/MDMS/MDMSService/egov-mdms-service/v1/_search": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:746)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)

**Comment by petkivim** [comment]
What Security Server Docker image are you using? In the [`niis/xroad-security-server-sidecar`](https://hub.docker.com/r/niis/xroad-security-server-sidecar/) image the `http` port is `8080` and `https` port `8443`.

**Comment by mithunhegde-egov** [comment]
no using this one for testing- https://hub.docker.com/r/niis/xroad-security-server

**Comment by petkivim** [comment]
Also that image uses ports `8080` and `8443` now. Unfortunately, the documentation on Docker Hub wasn't up-to-date. These are the correct mappings: 

```
docker run -p 8080:8080 -p 8443:8443 -p 4000:4000 -p 5500:5500 -p 5577:5577 --name my-ss niis/xroad-security-server
```

**Comment by mithunhegde-egov** [comment]
I am getting this error trying to connect to the provider- have two security servers running in the same machine mapped to different ports and central server is also running in the same machine. 
Caused by: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Server Error: [{"type":"Server.ServerProxy.NetworkError","message":"Connect to <provider_system_ip>:8094 [/<provider_system_ip>] failed: Connection timed out (Connection timed out)","detail":"8741ddd9-30b2-4a01-86b7-fcc18373517d"}]
is it because of the provider service or issue with the security server setup? I looked for Server.ServerProxy.NetworkError. similar errors are in the doc but not this exact one.

**Comment by petkivim** [comment]
It looks like the provider Security Server is not able to connect to the service. You should check that the provider Security Server is able to establish connection to `<provider_system_ip>:8094`.

**Comment by mithunhegde-egov** [comment]
Hi, I am trying to find helm chart for security server deployment. Can you provide reference to helm chart or is there any other recommended way to deploy security server.

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! Unfortunately, we don't have helm charts for X-Road. Instead, you can use [this](https://github.com/nordic-institute/X-Road/tree/develop/ansible) Ansible playbook to deploy a single Security Server or an entire X-Road ecosystem. Alternatively, [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Sidecar/kubernetes_security_server_sidecar_user_guide.md) you can find instructions for Kubernetes.

**Comment by mithunhegde-egov** [comment]
Hi @petkivim I have a doubt. how do we secure the client and provider IDs generated? so the only change a consumer needs to make is append the header with client id and add the appropriate provider id in the request url right? basically anyone with the id can connect to the security server right? or do we have option to implement any authentication between the information system and security server.

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! It's strongly recommended to use mTLS in the communication between a client information system and the Security Server. In that way, it's possible to secure the communication and be sure that only authorised clients are able to access the subsystems. More information about the required configuration is available [here](https://docs.x-road.global/Manuals/ug-ss_x-road_6_security_server_user_guide.html#91-communication-with-service-consumer-information-systems).

**Comment by mithunhegde-egov** [comment]
Hi @petkivim I see there is readme steps for setting external database for sidecar security server in github. is the same available for security server docker image? want to setup external postgres db with docker image for security server. can you share if any steps are available for the same?

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! The Security Server Sidecar Docker image (`niis/xroad-security-server-sidecar`) is the official Docker image for the Security Server. Instead, the `niis/xroad-security-server` image is for test and development purposes only and it doesn't support an external database. To setup an external database with the Security Server Sidecar, please follow [these](https://github.com/nordic-institute/X-Road/blob/develop/doc/Sidecar/security_server_sidecar_user_guide.md#25-using-an-external-database) instructions.

**Comment by mithunhegde-egov** [comment]
okay thank you and regarding authentication between the information system and security server. 
"An X-Road organisation’s client information system Security Server acts as the entry point to all the X-Road services. The client information system is responsible for implementing an end user authentication and access control mechanism that complies with the requirements of the particular X-Road instance. The identity of the end user may be made available to the service provider by including it in the service request"
does this mean we have to implement our own authentication between information system and ss? or does tls take care of the same?

**Comment by petkivim** [comment]
> An X-Road organisation’s client information system Security Server acts as the entry point to all the X-Road services. The client information system is responsible for implementing an end user authentication and access control mechanism that complies with the requirements of the particular X-Road instance. The identity of the end user may be made available to the service provider by including it in the service request

The above refers to a data exchange use case that includes an enduser / a citizen that plays an active role in the data exchange. Here's more information about the topic:

> End-user authentication
>
> X-Road is a data exchange layer between information systems. Among other things, X-Road provides organization level and machine level authentication that is based on [Public Key Infrastructure (PKI)](https://en.wikipedia.org/wiki/Public_key_infrastructure). The identity of each organization and Security Server is verified using certificates that are issued by a trusted Certification Authority (CA) when an organization joins an X-Road ecosystem.
>
> In case X-Road is used as a data exchange layer in a process that involves end-users and require their authentication, service consumer and service provider are responsible for the authentication of the end-user. Usually, the service consumer must authenticate the user before sending a request via X-Road and then it’s up to the service provider to decide whether it requires some evidence regarding the authentication to be sent as a part of the service request, e.g. authentication token, session context etc. From X-Road’s point of view end-user authentication is completely transparent and in case some data regarding the authentication is sent within the messages X-Road does not verify or validate it in any way.

TLS authentication between the Security Server and the information system takes care of authentication on the system level. More information is available [here](https://docs.x-road.global/Manuals/ug-ss_x-road_6_security_server_user_guide.html#9-communication-with-information-systems). Instead, you need to implement enduser authentication by yourself if/when needed.

**Comment by mithunhegde-egov** [comment]
apiVersion: v1
kind: Pod
metadata:
  name: xroad-ss
  namespace: xroad
spec:
  containers:
  - name: xroad-ss
    image: niis/xroad-security-server-sidecar:7.4.0
    imagePullPolicy: "Always"
    env:
    - name: XROAD_TOKEN_PIN
      value: "<pin>"
    - name: XROAD_ADMIN_USER
      value: "<username>"
    - name: XROAD_ADMIN_PASSWORD
      value: "<password>"
    - name: XROAD_DB_HOST
      value: "127.0.0.1"
    - name: XROAD_LOG_LEVEL
      value: "INFO"
    ports:
    - containerPort: 8443
    - containerPort: 4000
    - containerPort: 5500
    - containerPort: 5577
    
    trying this single pod deployment in our environemtn is failing. 
    2023-12-28T06:41:55.649Z ERROR [xroad-confclient-service] [QuartzScheduler_Worker-2] o.n.xroad.schedule.RetryingQuartzJob - Error executing job.
java.io.FileNotFoundException: /etc/xroad/configuration-anchor.xml
    at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.initConfigurationAnchor(ConfigurationClient.java:105)
    at ee.ria.xroad.common.conf.globalconf.ConfigurationClient.execute(ConfigurationClient.java:79)
    at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.executeWithRetry(ConfigurationClientJob.java:62)
Wrapped by: org.quartz.JobExecutionException: java.io.FileNotFoundException: /etc/xroad/configuration-anchor.xml
    at ee.ria.xroad.common.conf.globalconf.ConfigurationClientJob.executeWithRetry(ConfigurationClientJob.java:76)
    at org.niis.xroad.schedule.RetryingQuartzJob.execute(RetryingQuartzJob.java:59)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2023-12-28T06:41:55.650Z INFO [xroad-confclient-service] [QuartzScheduler_Worker-2] e.r.x.c.c.g.ConfigurationClientMain$ConfigurationClientJobListener - job was executed result=DiagnosticsStatus(returnCode=125, prevUpdate=2023-12-28T06:41:55.649745Z, nextUpdate=2023-12-28T06:42:55.649783Z, description=null)
2023-12-28T06:41:59.354Z ERROR [xroad-opmonitor] [DefaultQuartzScheduler_Worker-2] e.r.x.c.c.g.VersionedConfigurationDirectory - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.nio.file.NoSuchFileException: /etc/xroad/globalconf/instance-identifier
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2023-12-28T06:41:59.357Z ERROR [xroad-opmonitor] [DefaultQuartzScheduler_Worker-2] e.r.x.c.c.g.GlobalConfUpdater - Error updating globalconf
ee.ria.xroad.common.CodedException: MalformedGlobalConf.InternalError: Could not read instance identifier of this security server
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.loadInstanceIdentifier(VersionedConfigurationDirectory.java:371)
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.<init>(VersionedConfigurationDirectory.java:89)
    at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:80)
2023-12-28T06:42:00.439Z WARN [xroad-proxy-ui-api] [main] o.s.s.c.a.web.builders.WebSecurity - You are asking Spring Security to ignore Mvc [pattern='/api/v1/openapi.yaml']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
2023-12-28T06:42:10.597Z ERROR [xroad-proxy] [QuartzScheduler_Worker-2] e.r.x.c.c.g.VersionedConfigurationDirectory - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.nio.file.NoSuchFileException: /etc/xroad/globalconf/instance-identifier
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2023-12-28T06:42:10.597Z ERROR [xroad-proxy] [QuartzScheduler_Worker-2] e.r.x.c.c.g.GlobalConfUpdater - Error updating globalconf
ee.ria.xroad.common.CodedException: MalformedGlobalConf.InternalError: Could not read instance identifier of this security server
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.loadInstanceIdentifier(VersionedConfigurationDirectory.java:371)
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.<init>(VersionedConfigurationDirectory.java:89)
    at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:80)
2023-12-28T06:42:14.413Z ERROR [xroad-signer] [taskScheduler-1] e.r.x.c.c.g.VersionedConfigurationDirectory - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.nio.file.NoSuchFileException: /etc/xroad/globalconf/instance-identifier
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2023-12-28T06:42:14.413Z ERROR [xroad-signer] [taskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
ee.ria.xroad.common.CodedException: MalformedGlobalConf.InternalError: Could not read instance identifier of this security server
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.loadInstanceIdentifier(VersionedConfigurationDirectory.java:371)
    at ee.ria.xroad.common.conf.globalconf.VersionedConfigurationDirectory.<init>(VersionedConfigurationDirectory.java:89)
    at ee.ria.xroad.common.conf.globalconf.GlobalConfImpl.<init>(GlobalConfImpl.java:80)
    
    what might be the issue? is the sidecar supposed to run where the central server is running? trying in our internal org cluster

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! Have you tried to access the Security Server UI running in port `4000`? Errors about the instance identifier and configuration anchor are normal until the Security Server has been initialised.

**Comment by mithunhegde-egov** [comment]
I am not able to access. by port forwarding I can access the UI but frmo the aws host where the cluster is running it tthrows this error. 
Refused to apply style from 'https://<host-name>/assets/style-28d01c5c.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index-49c7dbc5.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
xroad:1 Refused to apply style from 'https://<host-name>/assets/style-28d01c5c.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
unable to make out if the issue is with the host environment or the application??

**Comment by petkivim** [comment]
I haven't come up with that kind of error message before. I'd say that it's related to your environment's configuration.

**Comment by mithunhegde-egov** [comment]
okay. thank you very much. that helps.

**Comment by mithunhegde-egov** [comment]
hello @petkivim, while deploying the sec server sidecar in the aws cluster we have ingress conflict with existing service which cannnot be modified. how can we overwrite the /#/login path?

**Comment by mithunhegde-egov** [comment]
Hi @petkivim we are using postgres v10.x as remote rds. when I login to the ss there is this http 500 error. I cannot find much in the proxy_ui_api.log about the error except for the 500 status in the post request. this might have to do anything with the version or the environment?

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! The supported PostgreSQL version depends on the X-Road software version and the operating system that you're using. For example, by default X-Road 7.3.x uses the following PostgreSQL versions on different operating systems:

- RHEL7: PostgreSQL 9
- RHEL8: PostgreSQL 10
- Ubuntu 20.04: PostgreSQL 12
- Ubuntu 22.04: PostgreSQL 14

You can find the default PostgreSQL versions from the X-Road Technologies document:

https://github.com/nordic-institute/X-Road/blob/7.3.2/doc/Architecture/arc-tec_x-road_technologies.md#5-security-server-technologies

Please note that you should change the tag according to the X-Road version that you're using.

**Comment by mithunhegde-egov** [comment]
[5] PostgreSQL version varies depending on operating system. By default, RHEL7 uses version 9, RHEL8 - 10, Ubuntu 20.04 - 12, Ubuntu 22.04 - 14. User may also use external PostgreSQL server.

latest security server version is being used(7.4.0) and Ubuntu 20.04. If we are using external remote db in this case PostgreSQL 12 needs to be used?  currently using postgres v10 remote db. can that be causing this error? AxiosError: Request failed with status code 500

**Comment by petkivim** [comment]
Yes, the Security Server version 7.4.0 on Ubuntu 20.04 requires PostgreSQL 12.

The error message (`AxiosError`) doesn't say a lot, it just means that a request to the management API failed for some reason. A more detailed reason for the error should be available in the `/var/log/xroad/proxy_ui_api.log` file.

**Comment by mithunhegde-egov** [comment]
yes I did check the logs. there is not detailed descritpion of the failure in the logs too.
![Screenshot from 2024-01-03 12-45-12](https://github.com/nordic-institute/X-Road/assets/152362871/4ca37501-4d56-4e86-820f-fe9df315d011)

**Comment by petkivim** [comment]
The screenshot is from the the `/var/log/xroad/proxy_ui_api_access.log` log file. Instead, you should look at the `/var/log/xroad/proxy_ui_api.log` log file.

**Comment by mithunhegde-egov** [comment]
this the only file present. proxy_ui_api.log file is missing the directory /var/log/xroad. checked for the hidden files too. but cannot find any other file other than the /var/log/xroad/proxy_ui_api_access.log. can it be present in any other location other than the one mentioned above?

**Comment by petkivim** [comment]
When running the Security Server in Docker on Kubernetes the `proxy_ui_api.log` must be accessed using `kubectl logs`. 

It seems that the problem is related to database authentication. When setting up the Security Server, have you followed these instructions:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Sidecar/kubernetes_security_server_sidecar_user_guide.md

**Comment by mithunhegde-egov** [comment]
yes followed the same steps but with the external db which is postgresql v10. I am getting the above error for this setup when I try to login with the given username and pwd.

**Comment by petkivim** [comment]
I'd recommend you to try with PostgreSQL 12 since it's the officially supported version. Also, you could try to further debug the issue by trying to establish a connection from inside the Security Server container to the database manually.

**Comment by mithunhegde-egov** [comment]
yes manually I am able to connect. do you suggest to use the PostgreSQL 12 and try??

**Comment by mithunhegde-egov** [comment]
Hi @petkivim we are getting ImagePullBackOff error. Is there a rate limiting? this is happening for security server sidecar kubernetes single pod deployment.

**Comment by petkivim** [comment]
The Docker Hub rate limits are available [here](https://docs.docker.com/docker-hub/download-rate-limit/). There shouldn't be other restrictions besides them.

**Comment by mithunhegde-egov** [comment]
okay. there is this error when I am trying to register a new sub system in the last configuration step. the 5500 port is listening on the server. what might the issue be about. central server is on an ec2 instance and security server sidecar has been deployed in our cluster.
2024-01-04T09:04:17.190Z ERROR [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-5] o.n.x.r.e.ApplicationExceptionHandler - exception caught
ee.ria.xroad.common.CodedException$Fault: Server.ClientProxy.NetworkError: Could not connect to any target host ([https://xroad-dev.digit.org:5500/])
	at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:141)
	at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
	at org.niis.xroad.common.managementrequest.ManagementRequestSender.getResponse(ManagementRequestSender.java:272)

**Comment by petkivim** [comment]
The error means that the Security Server where you're trying to register a subsystem is not able to establish a connection to the management Security Server port `5500`. This is the management Security Server URL that the client Security Server is using: `https://xroad-dev.digit.org:5500`. Either the URL is incorrect or there's something wrong with the firewall configurations.

**Comment by mithunhegde-egov** [comment]
I have a central server deployed with the docker image and two security servers deployed on two different clusters. those are the client and provider security servers. management security is the one deployed along with the central server or is it the one in the central server docker image?

**Comment by petkivim** [comment]
The management Security Server is the one where you have [registered the management services](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#3.8-Configuring-the-management-services).

The Security Server URL is initially defined when you send the authentication certificate registration request from the Security Server. Afterwards, you can change the URL on the Central Server in the Security Server details view.

**Comment by mithunhegde-egov** [comment]
okay. security serve fqdn is correct. there is no issue with that.  xroad-dev.digit.org is the security server name I have provided and same is reflected in the central server UI too. in the same security server I have registered the management services also. so the issue should be either with the port or the firewall? also if the client and management security server both are same then should it be https or http in the request https://xroad-dev.digit.org:5500??

**Comment by petkivim** [comment]
In that case, the most likely cause for the issue is incorrect firewall configuration. The client Security Server must be able to access ports `5500` and `5577` of the management Security Server. Connections to port `5500` use always `https` while connections to port `5577` use `http`.

**Comment by mithunhegde-egov** [comment]
there is this error I am getting now. what thjs one might be about? not able to register. port issue was resolved but getting this error now. the service is present.

2024-01-05T09:57:53.752Z INFO [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-5] ee.ria.xroad.common.AuditLogger - {"event":"Register client failed","user":"xrd","ipaddress":"192.168.77.49","reason":"Server.ServerProxy.UnknownService: Unknown service: SERVICE:EGOV/EGOV/1234/MANAGEMENT1/clientReg","warning":false,"auth":"Session","url":"/api/v1/clients/EGOV%3AEGOV%3A1234%3ANEWTEST/register","data":{"clientIdentifier":{"memberClass":"EGOV","memberCode":"1234","subsystemCode":"NEWTEST","fieldsForStringFormat":["EGOV","1234","NEWTEST"],"objectType":"SUBSYSTEM","xroadInstance":"EGOV"}}}
2024-01-05T09:57:53.752Z ERROR [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-5] o.n.x.r.e.ApplicationExceptionHandler - exception caught
ee.ria.xroad.common.CodedException$Fault: Server.ServerProxy.UnknownService: Unknown service: SERVICE:EGOV/EGOV/1234/MANAGEMENT1/clientReg
	at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:141)
	at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
	at org.niis.xroad.common.managementrequest.ManagementRequestSender.getResponse(ManagementRequestSender.java:272)

**Comment by petkivim** [comment]
The error message suggests that the management services haven't been configured under the management services subsystem (`EGOV/EGOV/1234/MANAGEMENT1`). Have you configured the management services following [these](https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0#3.8-Configuring-the-management-services) instructions?

Once the management services have been configured, the Services view of the subsystem should look like this:

![Screenshot 2024-01-05 at 12 06 37](https://github.com/nordic-institute/X-Road/assets/575897/cae8122a-fd47-470d-b2d2-bcd45a829f33)

**Comment by mithunhegde-egov** [comment]
yes that was resolved. if there are two security servers in two different cluster(one for provider and one for consumer is configured), the consumer is the management security server. now in this scenario in the provider security server do I have to provide the address of the management security server? and also is a management service necessary in provider security server in this scenario?

**Comment by petkivim** [comment]
It's enough to have one management Security Server so you don't need to configure the management services on the provider Security Server. Also, you don't need to configure the address of the management Security Server on the provider Security Server either.

**Comment by mithunhegde-egov** [comment]
ee.ria.xroad.common.CodedException$Fault: Server.ClientProxy.NetworkError: Could not connect to any target host ([https://<ip>:5500/])
at ee.ria.xroad.common.CodedException.fromFault(CodedException.java:141)
at ee.ria.xroad.common.message.SoapFault.toCodedException(SoapFault.java:130)
at org.niis.xroad.common.managementrequest.ManagementRequestSender.getResponse(ManagementRequestSender.java:272)
I am getting the same error here while trying to create subsystem and register. how do we configure this second security server in this case? added auth key, sign key imported the certs. any other steps are required for the second security server?? this is with another information system.

**Comment by petkivim** [comment]
Something is still wrong with the management Security Server related configuration. The address in the error message (`Could not connect to any target host ([https://:5500/])`) is empty while it should include the address of the management Security Server. 

Central Server

![Screenshot 2024-01-05 at 13 42 34](https://github.com/nordic-institute/X-Road/assets/575897/f36d4b87-e631-4dcb-99e4-6bc620569a8d)

Management Security Server

![Screenshot 2024-01-05 at 13 42 50](https://github.com/nordic-institute/X-Road/assets/575897/8534555c-2f84-4e70-8d8f-1ef2e210236d)

![Screenshot 2024-01-05 at 13 45 52](https://github.com/nordic-institute/X-Road/assets/575897/d0006158-768e-48de-b6c2-01dbbfc8a914)

**Comment by mithunhegde-egov** [comment]
ip address was missed.  Could not connect to any target host ([https://management_security_ip_address:5500/]) is correct. there is management security server ip address and everything in the pictures are as it is.
the management security server will be acting as consumer in our case and I am now trying to configure a provider security server registered to the same central server in a different environment and trying to establish connection between the two security servers. the second security server is throwing this error.

**Comment by petkivim** [comment]
In that case, the problem is that the provider Security Server is not able to establish a connection to the management Security Server port `5500`. Have you checked that the management Security Server ports `5500` and `5577` are accessible from the provider Security Server?

**Comment by mithunhegde-egov** [comment]
Hi @petkivim there is an issue with internal db creation hitting this error while trying to create the pod(security server sidecar k8s)

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles nontest are currently active).

2024-01-09 08:28:53,828 INFO exited: xroad-proxy-ui-api (exit status 1; not expected)
2024-01-09 08:28:54,830 INFO spawned: 'xroad-proxy-ui-api' with pid 1201
08:28:55.197 [main] INFO ee.ria.xroad.common.Version -- xroad-proxy-ui-api 7.4.0 (OpenJDK Runtime Environment 17 17.0.9+9-Ubuntu-120.04)
2024-01-09T08:28:55.976Z ERROR [xroad-proxy-ui-api] [main] o.n.x.r.c.PropertyFileReadingEnvironmentPostProcessor - Failed to process properties file: /etc/xroad/db.properties
java.io.FileNotFoundException: /etc/xroad/db.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)

**Comment by petkivim** [comment]
Unfortunately, using a `PersistentVolumeClaim` with the PostgreSQL directory (`/var/lib/postgresql/12/main`) isn't currently supported. Instead, it's recommended to use an external database.

**Comment by mithunhegde-egov** [comment]
okay. how can we make pod creation stateful in that case for the single pod sidecar k8s with internal database? whenever the pod gets recreated it loses the state which so we are unable to retain the state.

**Comment by petkivim** [comment]
You can use a `PersistentVolumeClaim` for the Security Server configuration (`/etc/xroad`) and message log archive (`/var/lib/xroad`) directories. When it comes to the database, you need to use an external one.

**Comment by mithunhegde-egov** [comment]
Hi @petkivim we are using kubernetes secret to provide credentials for PostgreSQL authentication. modified the yaml file in the docs to add this. getting this authentication issue becuase of the same
4-01-11T09:07:52.594Z WARN [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-6] o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 08004
2024-01-11T09:07:52.594Z ERROR [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-6] o.h.e.jdbc.spi.SqlExceptionHelper - The server requested password-based authentication, but no password was provided by plugin null
2024-01-11T09:07:52.594Z ERROR [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-6] o.n.x.s.r.s.NotificationService - getting soft token pin status failed
2024-01-11T09:07:52.594Z ERROR [xroad-proxy-ui-api] [https-jsse-nio-4000-exec-6] e.r.x.c.c.g.VersionedConfigurationDirectory - Failed to read instance identifier from /etc/xroad/globalconf/instance-identifier
java.nio.file.NoSuchFileException: /etc/xroad/globalconf/instance-identifier
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)

Using kubernetes secrret is supported right?

**Comment by mithunhegde-egov** [comment]
okay db credneitals are provided with configmap and secret like this. Configmap can be used and this should be working fine correct?

apiVersion: v1
data:
  db-host: <aws host>
  db-name: unifieddevdb
  db-url: <rds db url>
kind: ConfigMap
metadata:
  name: xroad-config
  namespace: xroad

---
apiVersion: v1
data:
  password: <secret pwd>
  username: <secret uname>
kind: Secret
metadata:
  name: db
  namespace: xroad
type: Opaque

**Comment by petkivim** [comment]
Please refer to the configuration samples in the Sidecar documentation. Also other alternative approaches may work, but we don't provide support for them.

**Comment by mithunhegde-egov** [comment]
yes trying to deploy using the same documentation. this is what is in the db.properties file. the password is supposed to be stored in this?? it is missing attaching the yaml used for creating the statefulset.

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@xroad-ss-0:/# cat /etc/xroad/db.properties
serverconf.hibernate.connection.username= unifieddev_serverconf
serverconf.hibernate.connection.url = jdbc:postgresql://unified-dev-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddev_serverconf
op-monitor.hibernate.connection.username= unifieddev_op-monitor
op-monitor.hibernate.connection.url = jdbc:postgresql://unified-dev-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddev_op-monitor
messagelog.hibernate.connection.username= unifieddev_messagelog
messagelog.hibernate.connection.url = jdbc:postgresql://unified-dev-db.czvokiourya9.ap-south-1.rds.amazonaws.com:5432/unifieddev_messagelog



yaml:

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xroad-ss
  namespace: xroad
spec:
  serviceName: xroad-service # Service name remains unchanged
  replicas: 1 # Updated to 3 replicas
  selector:
    matchLabels:
      app: xroad
  template:
    metadata:
      labels:
        app: xroad
    spec:
      containers:
      - name: xroad-ss
        image: niis/xroad-security-server-sidecar:7.4.0
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: 8Gi 
        env:
        - name: XROAD_TOKEN_PIN
          value: "1234"
        - name: XROAD_ADMIN_USER
          value: "xrd"
        - name: XROAD_ADMIN_PASSWORD
          value: "secret"
        - name: XROAD_LOG_LEVEL
          value: "INFO"
        - name: XROAD_DB_HOST
          value : "hostname"
        - name: XROAD_DB_PORT
          value: "5432"
        - name: XROAD_DB_PWD
          value: "externaldb pwd"
        - name: XROAD_DATABASE_NAME
          value: "unifieddev"        
        ports:
        - containerPort: 8443
        - containerPort: 4000
        - containerPort: 5500
        - containerPort: 5577

the passwords are missing in the file when the pod is created and the database names get appended too.

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! When starting the container, you need to provide the external database server hostname, server port, and superuser credentials (for creating the necessary users and tables) as parameters. The supported parameters are `XROAD_DB_PORT`,  `XROAD_DB_HOST` and `XROAD_DB_PWD`. The `serverconf`, `op-monitor` and `messagelog` databases are created automatically when the container is started if the provided parameter values are correct and connection to the remote database is established successfully.

**Comment by mithunhegde-egov** [comment]
Hi @petkivim trying to connect to rds. for aws rds superuser will not exist. the user provided has all roles true except superuser. what can we do in this case? other option is to install a postgresql db in an EC2 instance. but I wanted to understand what credentials can be passed with RDS instance for remote db sidecar deployment.

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! You can use the user that's provided in the deployment. Just make sure that the username is `postgres` and it should work fine.

**Comment by mithunhegde-egov** [comment]
okay. created a user with name postgres and granted all permissions granted in rds. I get this error with that

    Configuring groups
    Database and user exists, skipping database creation.
    Liquibase Home: /usr/share/xroad/db
    Starting Liquibase at 11:05:27 (version 4.19.0 #6648 built at 2023-01-17 15:02+0000)
    Unexpected error running Liquibase: ERROR: permission denied for schema serverconf
      Position: 14 [Failed SQL: (0) CREATE TABLE serverconf.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
    For more information, please use the --logLevel flag
    Running database migrations failed, please check database availability and configuration in /etc/xroad/db.properties and /etc/xroad/xroad.properties
    Database and user exists, skipping database creation.
    Liquibase Home: /usr/share/xroad/db
    Starting Liquibase at 11:05:32 (version 4.19.0 #6648 built at 2023-01-17 15:02+0000)
    Unexpected error running Liquibase: ERROR: permission denied for schema messagelog
      Position: 14 [Failed SQL: (0) CREATE TABLE messagelog.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (ID))]
    For more information, please use the --logLevel flag
    Running database migrations failed, please check database availability and configuration in /etc/xroad/db.properties and /etc/xroad/xroad.properties
    psql: error: could not connect to server: No such file or directory
    	Is the server running locally and accepting

**Comment by petkivim** [comment]
I just tested with RDS and the default user (username `postgres`) worked without problems without adjusting the permissions. I just created the RDS instance and spinned up a new Sidecar container. I didn't need to do any configuration changes to RDS. I did the test with Docker desktop:

```
docker run --detach \     
  --name ss \
  -p 4000:4000 \
  -p 5588:5588 \
  -p 8080:8080 \
  -p 8443:8443 \
  -p 5500:5500 \
  -p 5577:5577 \
  -e XROAD_TOKEN_PIN=<TOKEN_PIN> \
  -e XROAD_ADMIN_USER=<ADMIN_USER> \
  -e XROAD_ADMIN_PASSWORD=<ADMIN_PASSWORD> \
  -e XROAD_LOG_LEVEL=INFO \
  -e XROAD_DB_HOST=xxxx.xxxxxx.eu-north-1.rds.amazonaws.com \
  -e XROAD_DB_PORT=5432 \
  -e XROAD_DB_PWD=<DB_PASSWORD> \
  niis/xroad-security-server-sidecar:7.4.0
```

**Comment by mithunhegde-egov** [comment]
okay. but in sidecar kubernetes I am trying. not docker container. trying to pass the username and password as secret. There is no major difference in kubernetes deployment and docker container for remote db? I have passed all required parameters as above.

**Comment by mithunhegde-egov** [comment]
we are trying with sidecar kubernetes installation for security server. There was missing extension hstore in the postgreSQL database and there was same error in the log. adding the extension manually resolved the db migration issues during the creation of kubernetes statefulset with external db.

**Comment by mithunhegde-egov** [comment]
hi @petkivim when trying to create an ingress rule with a hostname (xroad-dev.digit.org) by default I have created a service and ingress forwards to port 4000. I created another rule for 5500 port also. But I want to understand when a security server tries to contact management security server, will it append port 5500 to the management security server address that is provided??

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! When a Security Server communicates with another Security Server, it establishes connection to the target Security Server ports `5500` and `5577`. This applies to the connections from your Security Server to the management Security Server too. The Security Server in the client role appends the port number automatically to the management Security Server address.

**Comment by mithunhegde-egov** [comment]
Hi @petkivim I am getting this ssl error when trying to register. could not find about this exact error when tried checking in the error docs. seems like the issue is when security server is trying to contact management secuirty server in the aws cluster. It is expecting the org's tls certificate for authentication right? can it be disabled for testing??

2024-01-19T05:32:52.777Z WARN [xroad-proxy] [qtp239824711-42] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Failed to connect to https://<external ip if the pod>:5500/
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.Socket.connect(Socket.java:633)
Wrapped by: ee.ria.xroad.common.CodedException: SslAuthenticationFailed.InternalError: Connect timed out
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:168)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getOcspResponses(AuthTrustVerifier.java:151)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verifyAuthCert(AuthTrustVerifier.java:105)
2024-01-19T05:32:52.777Z ERROR [xroad-proxy] [qtp239824711-42] e.r.x.p.c.FastestConnectionSelectingSSLSocketFactory - Could not connect to any target host ([https://<external ip of the pod>:5500/])
2024-01-19T05:32:52.777Z ERROR [xroad-proxy] [qtp239824711-42] e.r.x.p.c.AbstractClientProxyHandler - Request processing error (379aa02d-4e06-4a22-a41b-2ee5d86643e0)
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.Socket.connect(Socket.java:633)
Wrapped by: ee.ria.xroad.common.CodedException: Server.ClientProxy.SslAuthenticationFailed.InternalError: Connect timed out
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getAndCacheOcspResponses(AuthTrustVerifier.java:168)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.getOcspResponses(AuthTrustVerifier.java:151)
	at ee.ria.xroad.proxy.clientproxy.AuthTrustVerifier.verifyAuthCert(AuthTrustVerifier.java:105)
2024-01-19T05:32:52.778Z ERROR [xroad-proxy] [qtp239824711-42-soap] e.r.x.p.c.ClientMessageProcessor - onError()

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! It's a firewall configuration issue. The client Security Server is not able to establish connection to the management Security Server port `5577`. Please check your firewall and network configuration.

**Comment by mithunhegde-egov** [comment]
Hi @petkivim getting this below error when trying to pull the latest image 7.4.1

2024-02-06T09:03:02.840Z ERROR [xroad-proxy-ui-api] [main] o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles nontest are currently active).

2024-02-06 09:03:02,866 INFO exited: xroad-proxy-ui-api (exit status 1; not expected)
2024-02-06 09:03:03,868 INFO spawned: 'xroad-proxy-ui-api' with pid 2080
09:03:04.238 [main] INFO ee.ria.xroad.common.Version -- xroad-proxy-ui-api 7.4.1 (OpenJDK Runtime Environment 17 17.0.9+9-Ubuntu-120.04)

seems like UI has exit status 1. running the sidecar security server contianer 7.4.1

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! Have you followed the instructions defined [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Sidecar/kubernetes_security_server_sidecar_user_guide.md#7-version-update)?

**Comment by mithunhegde-egov** [comment]
Hi @petkivim when we add the management security server address in the consumer, it appends :5500 to it right? is there a way we can remove that and make it communicate with the address we provide directly?

**Comment by petkivim** [comment]
Hi @mithunhegde-egov ! Yes, the consumer Security Server appends ports `5500` and `5577` to the management Security Server automatically. Those port numbers are configurable, but it means that you have to change them for all the Security Servers. It's not possible to change the ports for the management Security Server only.

**Comment by mithunhegde-egov** [comment]
yes even if it is for all of them where can it be done? we will handle the requests internally once the request is in the cluster where security server is.

**Comment by petkivim** [comment]
You should look at the following properties and override their default values using the `/etc/xroad/conf.d/local.ini` configuration file. More information about the properties is available [here](https://docs.x-road.global/Manuals/ug-syspar_x-road_v6_system_parameters.html#32-proxy-parameters-proxy). However, I do not recommend changing the default values. 



```
[proxy]
server-listen-port=5500
server-port=5500
ocsp-responder-port=5577
```

**Comment by petkivim** [comment]
Hi @mithunhegde-egov! That error message just means that the Security Server hasn't been initialized yet. However, it doesn't say why uploading the configuration anchor failed. The most common reason is that the Security Server is not able to establish connection to the Central Server ports `80` and `443`.

**Comment by mithunhegde-egov** [comment]
uploading configuration I am getting a successfull message but unable to fetch member class. option to enter the code is also disabled in the UI as can be seen in the screenshot
![Screenshot from 2024-02-12 16-49-49](https://github.com/nordic-institute/X-Road/assets/152362871/a76be8ad-733b-4efc-9092-dee5c0c3e2d8)

**Comment by petkivim** [comment]
In that case, it's a different issue. You should check the logs for details.

**Comment by mithunhegde-egov** [comment]
yes the migrations are failing. that is the understanding from the logs. db migrations are failing. serverconf and messagelog db is present with all previleges applied and credentials I have checked in the /etc/xroad.properties file and /etc/xroad/db.properties file.

**Comment by raits** [comment]
Closing this issue since it is inactive.
